### ISSUE TITLE
saving user name in local storage/cache

### ISSUE THREAD

**Issue by amirfahoum** [WebAhead5/Pokemon-War#37]
Nice work  guys,
i have a small notice , how I see you save the user data on the browser cache  so every time you enter the game the page display Welcome "name" , I suggest that you should create  a small button that changes the user name , because if there are more users that using the same PC  the same message will appears for every user , 
so I think you should clear the cookies /cache every time you exit the game
or a small box that gett user input every time..

**Comment by Marwanrizik91** [comment]
yeah we actually thought about that, but i added the local storage just 1 hour before the code review thing.
one thing to mention, there are no cookies involved here. only local storage.
